version: "3.7"
services:
  app:
    build:
      args:
        user: domino
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: domino
    container_name: domino-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - domino

  domino-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: domino-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - domino

  nginx:
    image: nginx:alpine
    container_name: domino-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - domino

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: domino-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - domino-mysql
    networks:
      - domino
networks:
  domino:
    driver: bridge
